### ISSUE TITLE
Cannot launch mhc3 

### ISSUE THREAD

**Issue by fcapozzi** [Microchip-MPLAB-Harmony/mhc#13]
Linux Opensuse Leap 15.1
MPLABX 5.3 

This is the report 
`Path:         /home/fabio/Microchip-MPLAB-Harmony/mhc
Launch Stage: Generating Configuration Database

System Information:
Processor Information:
  ID: null
  Architecture: null
  Mode: null
  Count: null
Operating System Information:
  Name: Linux
  Version: 4.12.14-lp151.28.36-default
  Architecture: amd64
Available processors (cores): 2
Free memory (bytes): 266135264
Maximum memory (bytes): 1016463360
Total memory available to JVM (bytes): 777433088
Exception Information:
java.lang.Exception: java.lang.Exception: java.lang.NoClassDefFoundError: org/python/util/PythonInterpreter
Stack Trace:
java.lang.Exception: java.lang.Exception: java.lang.NoClassDefFoundError: org/python/util/PythonInterpreter
	at com.microchip.mh3.mplx_launcher.core.CoreIDE.parseDatabase(CoreIDE.java:1298)
	at com.microchip.mh3.mplx_launcher.core.CoreIDE$23.run(CoreIDE.java:671)
	at com.microchip.utils.task.TaskManager.update(TaskManager.java:117)
	at com.microchip.utils.task.TaskManager.access$000(TaskManager.java:9)
	at com.microchip.utils.task.TaskManager$1.run(TaskManager.java:198)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at org.netbeans.core.TimableEventQueue.dispatchEvent(TimableEventQueue.java:159)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:109)
	at java.awt.WaitDispatchSupport$2.run(WaitDispatchSupport.java:190)
	at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:235)
	at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:233)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.awt.WaitDispatchSupport.enter(WaitDispatchSupport.java:233)
	at java.awt.Dialog.show(Dialog.java:1084)
	at java.awt.Component.show(Component.java:1671)
	at java.awt.Component.setVisible(Component.java:1623)
	at java.awt.Window.setVisible(Window.java:1014)
	at java.awt.Dialog.setVisible(Dialog.java:1005)
	at com.microchip.mh3.mplx_launcher.core.CoreIDE.startup(CoreIDE.java:693)
	at com.microchip.mh3.mplx_launcher.Launcher.launch(Launcher.java:46)
	at com.microchip.mplab.modules.mh3.MHCLauncher.Launch(MHCLauncher.java:217)
	at com.microchip.mplab.modules.mh3.MHCLauncher.PreLaunch(MHCLauncher.java:128)
	at com.microchip.mplab.modules.mh3.MH3OpenActionPerformed.actionPerformed(MH3OpenActionPerformed.java:23)
	at org.openide.awt.AlwaysEnabledAction$1.run(AlwaysEnabledAction.java:199)
	at org.openide.util.actions.ActionInvoker$1.run(ActionInvoker.java:95)
	at org.openide.util.actions.ActionInvoker.doPerformAction(ActionInvoker.java:116)
	at org.openide.util.actions.ActionInvoker.invokeAction(ActionInvoker.java:99)
	at org.openide.awt.AlwaysEnabledAction.actionPerformed(AlwaysEnabledAction.java:202)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.AbstractButton.doClick(AbstractButton.java:376)
	at javax.swing.plaf.basic.BasicMenuItemUI.doClick(BasicMenuItemUI.java:842)
	at javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(BasicMenuItemUI.java:886)
	at java.awt.Component.processMouseEvent(Component.java:6539)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6304)
	at java.awt.Container.processEvent(Container.java:2239)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2297)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4904)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4535)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4476)
	at java.awt.Container.dispatchEventImpl(Container.java:2283)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:760)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:84)
	at java.awt.EventQueue$4.run(EventQueue.java:733)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:730)
	at org.netbeans.core.TimableEventQueue.dispatchEvent(TimableEventQueue.java:159)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: java.lang.Exception: java.lang.NoClassDefFoundError: org/python/util/PythonInterpreter
	at com.microchip.mh3.database.Database.initialize(Database.java:212)
	at com.microchip.mh3.mplx_launcher.core.CoreIDE.parseDatabase(CoreIDE.java:1286)
	... 75 more
Caused by: java.lang.NoClassDefFoundError: org/python/util/PythonInterpreter
	at com.microchip.h3.database.module.Module.<init>(Module.java:84)
	at com.microchip.h3.database.module.CSPModule.<init>(CSPModule.java:29)
	at com.microchip.h3.database.module.Module.ParseCSPModule(Module.java:543)
	at com.microchip.h3.database.module.CSPModule.Parse(CSPModule.java:83)
	at com.microchip.h3.database.ModuleManager.parseFramework(ModuleManager.java:221)
	at com.microchip.h3.database.ConfigurationDatabase.parseFramework(ConfigurationDatabase.java:377)
	at com.microchip.mh3.database.Database.initialize(Database.java:197)
	... 76 more
Caused by: java.lang.ClassNotFoundException: org.python.util.PythonInterpreter
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 83 more
`

**Comment by sandeepm1** [comment]
Thanks for reporting. Are you still facing this issue with new released version 3.4.0.
