### ISSUE TITLE
New Project flow failing to generate harmony.prj file

### ISSUE THREAD

**Issue by SamSiegel** [Microchip-MPLAB-Harmony/mhc#17]
Creating a new project builds the required project directories and creates the project inside MPLabX, but does not generate a file that is required to open harmony configurator, harmony.prj.
I've only received the failure while targeting an ATSAMD21J18 (which I haven't done previously), so I'm unsure whether other (previously working on my system) devices will work.  

Failure window text dump:

Path:         C:\Users\siege\Harmony3\mhc
Launch Stage: Loading Configuration Data

System Information:
Processor Information:
  ID: AMD64 Family 23 Model 113 Stepping 0, AuthenticAMD
  Architecture: AMD64
  Mode: null
  Count: 16
Operating System Information:
  Name: Windows 10
  Version: 10.0
  Architecture: amd64
Available processors (cores): 16
Free memory (bytes): 435778272
Maximum memory (bytes): 8457682944
Total memory available to JVM (bytes): 1437073408
Exception Information:
java.lang.Exception: Unable to launch Harmony tool suite for this configuration.  The harmony.prj file is missing at: C:\Users\siege\HarmonyProjects\MyProject\firmware\src\config\default\harmony.prj
Stack Trace:
java.lang.Exception: Unable to launch Harmony tool suite for this configuration.  The harmony.prj file is missing at: C:\Users\siege\HarmonyProjects\MyProject\firmware\src\config\default\harmony.prj
	at com.microchip.mh3.mplx_launcher.core.CoreIDE$22.run(CoreIDE.java:665)
	at com.microchip.utils.task.TaskManager.update(TaskManager.java:117)
	at com.microchip.utils.task.TaskManager.access$000(TaskManager.java:9)
	at com.microchip.utils.task.TaskManager$1.run(TaskManager.java:198)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at org.netbeans.core.TimableEventQueue.dispatchEvent(TimableEventQueue.java:159)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:109)
	at java.awt.WaitDispatchSupport$2.run(WaitDispatchSupport.java:190)
	at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:235)
	at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:233)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.awt.WaitDispatchSupport.enter(WaitDispatchSupport.java:233)
	at java.awt.Dialog.show(Dialog.java:1084)
	at java.awt.Component.show(Component.java:1671)
	at java.awt.Component.setVisible(Component.java:1623)
	at java.awt.Window.setVisible(Window.java:1014)
	at java.awt.Dialog.setVisible(Dialog.java:1005)
	at com.microchip.mh3.mplx_launcher.core.CoreIDE.startup(CoreIDE.java:707)
	at com.microchip.mh3.mplx_launcher.Launcher.launch(Launcher.java:46)
	at com.microchip.mplab.modules.mh3.MHCLauncher.Launch(MHCLauncher.java:217)
	at com.microchip.mplab.modules.mh3.MHCLauncher.PreLaunch(MHCLauncher.java:128)
	at com.microchip.mplab.modules.mh3.MHCAutoLauncher$1$1.run(MHCAutoLauncher.java:62)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at org.netbeans.core.TimableEventQueue.dispatchEvent(TimableEventQueue.java:159)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by aethaniel** [comment]
@SamSiegel, you may have missed in the release notes of MHC v3.6.0 we changed the format of MHC project file from previous prj to a whole .mhc folder containing YAML files. New version is reading old files and convert them.

Your issue looks like you didn't update the Harmony plugin in MPLAB X to its latest version (v3.6.1), as documented in release notes. You may have missed the popup about it in MPLAB X.

Can you update it and tell me if you still have the problem?

Thanks

**Comment by aethaniel** [comment]
no answer in 16d, I consider my answer solved the problem, thus closing this ticket.

**Comment by htennek2k** [comment]
Hello, 

Just happened to have the same issue, with MPLAB X 6.00, XC32 4.21, and latest version of harmony 3 (plug in version 3.6.4)

Any clue on how to deal with this? Thank you.

**Comment by aethaniel** [comment]
Hi, MHC is not maintained anymore in profit of MCC. You may have seen the popup dialog at the start.

Can you give a try to MCC, please?

**Comment by htennek2k** [comment]
Thank you for your reply. 

Sorry, but didn't really understand what you meant. 

This means creating the project under MCC Harmony, and then try the MCode Configurator (and no longer MHC?)

**Comment by htennek2k** [comment]
Okay, 

It seems I got it working so, will replicate my steps here:

1. uninstalled MPLAB X 6.00 (deleting all persistent folders)
2. Installed MPLAB X 6.05.
3. kept my Microchip/Harmony3 directory untouched.
4. Created new project using MCC 32 Harmony Project
5. Selected Harmony3 directory (as above) and repository

MCC loads automatically thereafter.

Thanks @aethaniel for your suggestion.

Now, harmony3 plug in doesn't even show up in MPLAB X.
